### ISSUE TITLE
Microphone does not work on Windows

### ISSUE THREAD

**Issue by breandan** [cmusphinx/sphinx4#33]
The DialogDemo has been broken for several months, throwing with the following exception on Windows:

```
Exception in thread "main" java.lang.IllegalStateException: javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at edu.cmu.sphinx.api.Microphone.<init>(Microphone.java:38)
	at edu.cmu.sphinx.api.SpeechSourceProvider.getMicrophone(SpeechSourceProvider.java:18)
	at edu.cmu.sphinx.api.LiveSpeechRecognizer.<init>(LiveSpeechRecognizer.java:35)
	at edu.cmu.sphinx.demo.dialog.DialogDemo.main(DialogDemo.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:413)
	at edu.cmu.sphinx.api.Microphone.<init>(Microphone.java:36)
	... 8 more
```

This issue makes it impossible to stop recording on a LiveSpeechRecognizer and reuse the same microphone on Windows. According to @nshmyrev, this is due to be fixed soon https://sourceforge.net/p/cmusphinx/bugs/412/.

Related
* [LineUnavailableException while running dialog Sample after setting up Sphinx](https://sourceforge.net/p/cmusphinx/discussion/sphinx4/thread/b31b5b35/)
* [Stop (not pause) LiveSpeechRecognizer?](https://sourceforge.net/p/cmusphinx/discussion/sphinx4/thread/c76b3d1c/)
* [Can't access microphone while running Dialog demo in sphinx4 5prealpha](http://stackoverflow.com/questions/29121188/cant-access-microphone-while-running-dialog-demo-in-sphinx4-5prealpha)

**Comment by nshmyrev** [comment]
Thank you for your report, there is no need to file duplicates.
