### ISSUE TITLE
Problem with java version

### ISSUE THREAD

**Issue by Jennifer03** [cmusphinx/sphinx4#46]
I can't upgrade to java 8 and sphinx4 to work with java8. I am getting following error while running TranscriberDemo ::

```Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/cmu/sphinx/api/Configuration : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.pericent.test.TranscriberDemo.main(TranscriberDemo.java:16)```

**Comment by nshmyrev** [comment]
It seems you are trying to run the code compiled with Java 8 in Java 7 JRE. Make sure your java runtime is also upgraded.

To get more help on this issue provide more information about how do you compile and run java code. Are you using IDE or command line, what are options and so on.

**Comment by nshmyrev** [comment]
Ok, I understood what you meant from your SO question. I have committed an update to set version to Java 7 and pushed jars, if you update it should work now.

**Comment by Jennifer03** [comment]
I have updated my project but still getting same error.

**Comment by nshmyrev** [comment]
run mvn install -U, it should update sphinx4 jars. You can also delete sphinx4 jars from you local .m2 repo
