### ISSUE TITLE
NullPointerException crushes Sphinx on limited vocabulary

### ISSUE THREAD

**Issue by agur** [cmusphinx/sphinx4#51]
edu.cmu.sphinx.frontend.feature.LiveCMN#sum was missing which resulted in NPEs in some cases.  

- [ ] 1. [Similar report on sourceforge](https://sourceforge.net/p/cmusphinx/discussion/sphinx4/thread/15f197a2/) - can close the loop there once this is fixed.
- [ ] 2.  Reproduce - just pointed it to an mp3 file I had locally and it crashed on that one.  But can't post that mp3.  If anyone has one handy - please add.
- [x] 3. Figure a code fix to allow it not to crush.
- [x] 4.  Pass tests locally.
- [ ] 5.  Pull Request
  - [x] Filed #52
  - [ ] Review / Update
  - [ ] Merge

```
Exception in thread "main" java.lang.NullPointerException
	at edu.cmu.sphinx.frontend.feature.LiveCMN.normalize(LiveCMN.java:203)
	at edu.cmu.sphinx.frontend.feature.LiveCMN.getData(LiveCMN.java:182)
	at edu.cmu.sphinx.frontend.feature.AbstractFeatureExtractor.getNextData(AbstractFeatureExtractor.java:125)
	at edu.cmu.sphinx.frontend.feature.AbstractFeatureExtractor.getData(AbstractFeatureExtractor.java:101)
	at edu.cmu.sphinx.frontend.feature.FeatureTransform.getData(FeatureTransform.java:85)
	at edu.cmu.sphinx.frontend.FrontEnd.getData(FrontEnd.java:222)
	at edu.cmu.sphinx.decoder.scorer.SimpleAcousticScorer.getNextData(SimpleAcousticScorer.java:146)
	at edu.cmu.sphinx.decoder.scorer.SimpleAcousticScorer.calculateScoresAndStoreData(SimpleAcousticScorer.java:104)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstLookaheadSearchManager.scoreFastMatchTokens(WordPruningBreadthFirstLookaheadSearchManager.java:286)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstLookaheadSearchManager.fastMatchRecognize(WordPruningBreadthFirstLookaheadSearchManager.java:206)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstLookaheadSearchManager.localStart(WordPruningBreadthFirstLookaheadSearchManager.java:244)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstSearchManager.startRecognition(WordPruningBreadthFirstSearchManager.java:274)
	at edu.cmu.sphinx.decoder.Decoder.decode(Decoder.java:62)
	at edu.cmu.sphinx.recognizer.Recognizer.recognize(Recognizer.java:106)
	at edu.cmu.sphinx.recognizer.Recognizer.recognize(Recognizer.java:122)
	at edu.cmu.sphinx.api.AbstractSpeechRecognizer.getResult(AbstractSpeechRecognizer.java:60)
	at edu.cmu.sphinx.demo.transcriber.TranscriberDemo.main(TranscriberDemo.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by agur** [comment]
Filed pull request #52 - please review.

Hey @nshmyrev - seems that it was introduced in b5e4ac7.  Please see if the logic is appropriate.
Only made the minimum to help it not to crash.  And while the tests have all passed, didn't have enough time or deep knowledge in the library to validate it's really correct.  

Code around the fixed logic is not straight forward, if someone got the cycles we may want to revise.

**Comment by mbait** [comment]
Looks good for me, but I am leaving it for @nshmyrev to accept.
