### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 161 	at edu.cmu.sphinx.decoder.search.WordPruningBreadthF

### ISSUE THREAD

**Issue by habtbog** [cmusphinx/sphinx4#90]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 161
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstLookaheadSearchManager.updateLookaheadPenalty(WordPruningBreadthFirstLookaheadSearchManager.java:479)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstLookaheadSearchManager.collectSuccessorTokens(WordPruningBreadthFirstLookaheadSearchManager.java:435)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstSearchManager.growBranches(WordPruningBreadthFirstSearchManager.java:396)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstSearchManager.localStart(WordPruningBreadthFirstSearchManager.java:371)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstLookaheadSearchManager.localStart(WordPruningBreadthFirstLookaheadSearchManager.java:246)
	at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstSearchManager.startRecognition(WordPruningBreadthFirstSearchManager.java:274)
	at edu.cmu.sphinx.decoder.Decoder.decode(Decoder.java:62)
	at edu.cmu.sphinx.recognizer.Recognizer.recognize(Recognizer.java:106)
	at edu.cmu.sphinx.recognizer.Recognizer.recognize(Recognizer.java:122)
	at edu.cmu.sphinx.api.AbstractSpeechRecognizer.getResult(AbstractSpeechRecognizer.java:60)
	at sphinx.Sphinx.main(Sphinx.java:37)
Java Result: 1

**Comment by nshmyrev** [comment]
Sorry, the information you provided is not sufficient to help you. Provide more information on what you done to get help.

**Comment by habtbog** [comment]
I got the same problem like https://sourceforge.net/p/cmusphinx/discussion/sphinx4/thread/a2ffb413/
