### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by njlr** [cmusphinx/sphinx4#95]
I cannot build the latest `master`: 

```bash
$ git clone git@github.com:cmusphinx/sphinx4.git 

$ cd ./sphinx4

$ git rev-parse HEAD
32df364ce3d9688c13a524981898931335d688e5

$ gradle build
> Task :sphinx4-core:compileJava 
/.../sphinx4/sphinx4-core/src/main/java/edu/cmu/sphinx/fst/sequitur/SequiturImport.java:24: error: package javax.xml.bind does not exist
import javax.xml.bind.JAXBContext;
                     ^

FAILURE: Build failed with an exception.

```

System info: 

```bash
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

$ gradle --version
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.5 compiled on March 28 2019
JVM:          11.0.4 (Ubuntu 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OS:           Linux 5.0.0-36-generic amd64
```

**Comment by njlr** [comment]
Looks like I needed to downgrade Java: 

```bash
$ sudo apt-get install openjdk-8-jdk  -y 

$ sudo update-java-alternatives -l
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.8.0-openjdk-amd64       1081       /usr/lib/jvm/java-1.8.0-openjdk-amd64

$ sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
```

Although some of the tests fail: 

>   DictionaryTest. testDictionary
>   LatticeCompTest. testLatticeComp

**Comment by roddar92** [comment]
Hi all,

I also couldn't build the project to see demo for JSGF, `resource:` protocol is not recognized by my Java.
How could I try sphinx JSGFs tool in another way?

Daria

**Comment by nshmyrev** [comment]
@roddar92 You'd better try https://github.com/alphacep/kaldi-websocket-python

**Comment by roddar92** [comment]
Thanks, Nickolay, I look it later)
It's a pity, but now I need any Java library with JSGF approach or another CFGs.

**Comment by solfung** [comment]
I got the same build test failures for testDictionary and testLatticeComp. These are excerpts from the logs:

Gradle suite > Gradle test > edu.cmu.sphinx.linguist.dictionary.DictionaryTest.testDictionary FAILED
     java.lang.AssertionError: 
     Expected: an array with size <2>
          but: array size was <1>
         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
         at edu.cmu.sphinx.linguist.dictionary.DictionaryTest.testDictionary(DictionaryTest.java:42)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
         at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
         at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
         at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
         at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
         at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
         at org.testng.TestRunner.privateRun(TestRunner.java:767)
         at org.testng.TestRunner.run(TestRunner.java:617)
         at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
         at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
         at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
         at org.testng.SuiteRunner.run(SuiteRunner.java:254)
         at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
         at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
         at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
         at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
         at org.testng.TestNG.run(TestNG.java:1057)
         at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
         at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
         at com.sun.proxy.$Proxy2.stop(Unknown Source)
         at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
         at java.lang.Thread.run(Thread.java:748)
 
.........

Gradle suite > Gradle test > edu.cmu.sphinx.result.LatticeCompTest.testLatticeComp FAILED
     java.lang.AssertionError: 
         at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
         at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
         at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
         at edu.cmu.sphinx.result.LatticeCompTest.testLatticeComp(LatticeCompTest.java:83)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
         at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
         at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
         at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
         at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
         at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
         at org.testng.TestRunner.privateRun(TestRunner.java:767)
         at org.testng.TestRunner.run(TestRunner.java:617)
         at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
         at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
         at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
         at org.testng.SuiteRunner.run(SuiteRunner.java:254)
         at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
         at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
         at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
         at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
         at org.testng.TestNG.run(TestNG.java:1057)
         at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
         at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
         at com.sun.proxy.$Proxy2.stop(Unknown Source)
         at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
